# Generated by Django 4.2.4 on 2023-09-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='speakerControl',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='word',
            name='translationControl',
            field=models.JSONField(default=list),
        ),
    ]
