# Generated by Django 4.2.4 on 2023-09-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_post_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coordinates',
        ),
    ]
