# Generated by Django 4.2.4 on 2023-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_remove_post_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
    ]
