# Generated by Django 4.2.4 on 2023-09-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0006_rename_title_post_imagefile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='words',
        ),
    ]
