# Generated by Django 4.2.4 on 2023-09-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0007_rename_content_post_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imageFile',
            new_name='imageName',
        ),
    ]
